default


_layouts/default.html  


<!doctype html>
<html>
  <head>
    <meta charset="utf-8"> 
    <title>{{ page.title }}</title>  
  </head> 
  <body>
    {{ content }} 




  </body>
</html>

theme  jekyll-theme-cayman
README.html

        # **measurevaluenotmoney/Sound money**

        ###### Measure length, not inches. Measure weight, not ounces.

        * *The primitive condition of mankind is FINANCIAL COMPLEXITY (BARTER ECONOMY).*

        * *By definition, no one ever changed the amount of money in the world, people decide what a standard of value is worth, not how much there is.*

        Evict measured money, NOT TENANTS (not VALUE!).

        Foreclose against measured money, NOT AGAINST PEOPLE WHO WANT TO OWN HOUSES (not against VALUE!).

gem install jekyll-admin
gem "github-pages", group   jekyll_plugins

