gem install jekyll-admin
gem "github-pages", group   jekyll_plugins
    
default


_layouts/default.html   
# **measurevaluenotmoney/Sound money**

###### Measure length, not inches. Measure weight, not ounces.

* *The primitive condition of mankind is "FINANCIAL COMPLEXITY (BARTER ECONOMY)".*

* *By definition, no one ever changed the amount of money in the world, people decide what a standard of value is worth, not how much there is.*

Evict measured money, NOT TENANTS (not VALUE!).

Foreclose against measured money, NOT AGAINST PEOPLE WHO WANT TO OWN HOUSES (not against VALUE!).

<!doctype html>
<html>
  <head>
    <meta charset="utf-8"> # **measurevaluenotmoney/Sound money**
    <title>{{ page.title }}</title>  # **measurevaluenotmoney/Sound money**
  </head> ###### Measure length, not inches. Measure weight, not ounces.
  <body>
    {{ content }} * *The primitive condition of mankind is FINANCIAL COMPLEXITY (BARTER ECONOMY).*

* *By definition, no one ever changed the amount of money in the world, people decide what a standard of value is worth, not how much there is.*

Evict measured money, NOT TENANTS (not VALUE!).

Foreclose against measured money, NOT AGAINST PEOPLE WHO WANT TO OWN HOUSES (not against VALUE!).
  </body>
</html>

theme  jekyll-theme-cayman

theme  jekyll-theme-cayman

theme jekyll-theme-cayman
